# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ac97df8a630c7db6a8d15168d3a2c3a9eb491956a86e01f19ebfb7ad613dbfb2126afab9f0130e333c9fc5c4aec3ce9106e9fc6017b6d1f70a706e27dbad0d

test:
  secret_key_base: 2c513c203efddda7dae84270a559f6ad20f8cfc922f87143682f999a8d2997bbb31076f540d51a8c9a1de5b202ccd9ff033274799e34b41b476f9cf66fec9399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
